#!/usr/bin/env python3
"""
Part 2: Additional translations for remaining Japanese text
"""

import re
from pathlib import Path

# Additional translation mappings
additional_translations = {
    # Remaining common Japanese phrases
    "を増やしても効率は改善しない": " does not improve efficiency even with more",
    "（n = ": "(n = ",
    "の収束速度": " convergence rate",
    "です。": ".",
    "は": " is",
    "が": " that",
    "を": " ",
    "に": " to",
    "の": " of",
    "と": " and",
    "や": " or",
    "で": " with",
    "から": " from",
    "より": " than",
    "として": " as",
    "により": " by",
    "について": " about",
    "における": " in",
    "に関する": " regarding",
    "による": " by",
    "によって": " by",
    "のための": " for",
    "での": " in",
    "への": " to",
    "からの": " from",
    "までの": " to",
    "との": " with",
    "という": " called",
    "といった": " such as",
    "といえる": " can be said",
    "である": " is",
    "ではない": " is not",
    "であり": " and",
    "でも": " even",
    "では": " in",
    "だが": " but",
    "しかし": "However",
    "また": "Also",
    "さらに": "Furthermore",
    "したがって": "Therefore",
    "なぜなら": "Because",
    "例えば": "For example",
    "つまり": "In other words",
    "ただし": "However",
    "もし": "If",
    "もちろん": "Of course",
    "特に": "Especially",
    "主に": "Mainly",
    "通常": "Usually",
    "一般的に": "Generally",
    "基本的に": "Basically",
    "実際に": "Actually",
    "具体的に": "Specifically",
    "詳しく": "in detail",
    "簡単に": "simply",
    "容易に": "easily",
    "困難": "difficult",
    "可能": "possible",
    "不可能": "impossible",
    "必要": "necessary",
    "重要": "important",
    "有効": "effective",
    "有用": "useful",
    "便利": "convenient",
    "効果的": "effective",
    "効率的": "efficient",
    "適切": "appropriate",
    "最適": "optimal",
    "理想的": "ideal",
    "現実的": "realistic",
    "実用的": "practical",
    "典型的": "typical",
    "代表的": "representative",
    "一般的": "general",
    "特別": "special",
    "顕著": "remarkable",
    "明確": "clear",
    "正確": "accurate",
    "詳細": "detailed",
    "簡潔": "concise",
    "複雑": "complex",
    "単純": "simple",
    "高度": "advanced",
    "初歩的": "elementary",
    "基礎的": "fundamental",
    "応用的": "applied",
    "理論的": "theoretical",
    "実験的": "experimental",
    "数値的": "numerical",
    "解析的": "analytical",
    "定量的": "quantitative",
    "定性的": "qualitative",

    # Specific remaining terms
    "です": "",
    "ます": "",
    "ました": "",
    "でした": " was",
    "ません": " not",
    "ませんでした": " was not",
    "でしょう": " will be",
    "だろう": " probably",
    "かもしれません": " may",
    "かもしれない": " might",
    "べき": " should",
    "なければならない": " must",
    "ことができる": " can",
    "ことができます": " can",
    "ことができました": " could",
    "ことが": " that",
    "ことは": " that",
    "ことを": " that",
    "ことに": " to",
    "ことで": " by",
    "ことから": " from",
    "ため": "purpose",
    "ように": "like",
    "ような": "like",
    "など": "etc.",
    "なお": "Note",
    "すなわち": "namely",
    "要するに": "in short",
    "結局": "after all",
    "最終的に": "finally",
    "最初に": "first",
    "次に": "next",
    "最後に": "finally",
    "まず": "first",
    "そして": "and",
    "それから": "then",
    "その後": "after that",
    "その結果": "as a result",
    "そのため": "therefore",
    "このように": "thus",
    "このため": "for this reason",
    "この場合": "in this case",
    "その場合": "in that case",
    "どの場合でも": "in any case",
    "いずれにしても": "in any case",
    "とにかく": "anyway",
    "すると": "then",
    "ところで": "by the way",
    "さて": "now",
    "では": "then",
    "それでは": "then",
    "そこで": "so",
    "しかしながら": "however",
    "にもかかわらず": "despite",
    "一方": "on the other hand",
    "他方": "on the other hand",
    "逆に": "conversely",
    "反対に": "on the contrary",
    "同様に": "similarly",
    "同じく": "likewise",
    "また": "also",
    "加えて": "in addition",
    "さらに": "furthermore",
    "その上": "moreover",
    "それに": "besides",
    "ただ": "just",
    "のみ": "only",
    "だけ": "only",
    "ばかり": "only",
    "すべて": "all",
    "全て": "all",
    "すべての": "all",
    "各": "each",
    "それぞれ": "each",
    "個々の": "individual",
    "様々な": "various",
    "いくつかの": "several",
    "多くの": "many",
    "少数の": "few",
    "いくらかの": "some",
    "ある": "certain",
    "特定の": "specific",
    "任意の": "arbitrary",
    "一定の": "constant",
    "同じ": "same",
    "異なる": "different",
    "別の": "another",
    "他の": "other",
    "新しい": "new",
    "古い": "old",
    "最新の": "latest",
    "従来の": "conventional",
    "既存の": "existing",
    "これまでの": "previous",
    "今後の": "future",
    "将来の": "future",
    "現在の": "current",
    "過去の": "past",
    "初期の": "initial",
    "最終的な": "final",
    "暫定的な": "provisional",
    "仮の": "temporary",
    "正式な": "official",
    "非公式な": "unofficial",
    "公開の": "public",
    "非公開の": "private",
    "秘密の": "secret",
    "機密の": "confidential",
    "重要な": "important",
    "主要な": "main",
    "中心的な": "central",
    "基本的な": "basic",
    "本質的な": "essential",
    "根本的な": "fundamental",
    "原理的な": "principled",
    "技術的な": "technical",
    "科学的な": "scientific",
    "数学的な": "mathematical",
    "物理的な": "physical",
    "化学的な": "chemical",
    "生物的な": "biological",
    "工学的な": "engineering",
    "医学的な": "medical",
    "経済的な": "economic",
    "社会的な": "social",
    "政治的な": "political",
    "法的な": "legal",
    "倫理的な": "ethical",
    "道徳的な": "moral",
    "文化的な": "cultural",
    "歴史的な": "historical",
    "伝統的な": "traditional",
    "革新的な": "innovative",
    "創造的な": "creative",
    "独創的な": "original",
    "画期的な": "groundbreaking",
    "革命的な": "revolutionary",
    "実用的な": "practical",
    "理論的な": "theoretical",
    "抽象的な": "abstract",
    "具体的な": "concrete",
    "直接的な": "direct",
    "間接的な": "indirect",
    "明示的な": "explicit",
    "暗黙的な": "implicit",
    "自動的な": "automatic",
    "手動的な": "manual",
    "自然な": "natural",
    "人工的な": "artificial",
    "合成的な": "synthetic",
    "有機的な": "organic",
    "無機的な": "inorganic",
    "生体": "biological",
    "非生体": "non-biological",
    "生きた": "living",
    "死んだ": "dead",
    "活性な": "active",
    "不活性な": "inactive",
    "安定な": "stable",
    "不安定な": "unstable",
    "平衡な": "equilibrium",
    "非平衡な": "non-equilibrium",
    "線形な": "linear",
    "非線形な": "nonlinear",
    "連続な": "continuous",
    "離散的な": "discrete",
    "有限な": "finite",
    "無限な": "infinite",
    "大きな": "large",
    "小さな": "small",
    "長い": "long",
    "短い": "short",
    "高い": "high",
    "低い": "low",
    "広い": "wide",
    "狭い": "narrow",
    "深い": "deep",
    "浅い": "shallow",
    "厚い": "thick",
    "薄い": "thin",
    "重い": "heavy",
    "軽い": "light",
    "強い": "strong",
    "弱い": "weak",
    "硬い": "hard",
    "軟らかい": "soft",
    "固い": "solid",
    "液体の": "liquid",
    "気体の": "gas",
    "熱い": "hot",
    "冷たい": "cold",
    "暖かい": "warm",
    "涼しい": "cool",
    "明るい": "bright",
    "暗い": "dark",
    "速い": "fast",
    "遅い": "slow",
    "早い": "early",
    "遅い": "late",
    "急な": "rapid",
    "緩やかな": "gradual",
    "突然の": "sudden",
    "徐々の": "gradual",
    "瞬間的な": "instantaneous",
    "持続的な": "sustained",
    "一時的な": "temporary",
    "永続的な": "permanent",
    "周期的な": "periodic",
    "不規則な": "irregular",
    "規則的な": "regular",
    "ランダムな": "random",
    "確率的な": "stochastic",
    "決定的な": "deterministic",
    "予測可能な": "predictable",
    "予測不可能な": "unpredictable",
    "既知の": "known",
    "未知の": "unknown",
    "明らかな": "obvious",
    "不明な": "unclear",
    "確実な": "certain",
    "不確実な": "uncertain",
    "正しい": "correct",
    "間違った": "incorrect",
    "適切な": "appropriate",
    "不適切な": "inappropriate",
    "妥当な": "reasonable",
    "不当な": "unreasonable",
    "合理的な": "rational",
    "非合理的な": "irrational",
    "論理的な": "logical",
    "非論理的な": "illogical",
    "整合的な": "consistent",
    "矛盾した": "contradictory",
    "一貫した": "consistent",
    "不一致な": "inconsistent",
    "統一的な": "unified",
    "分散した": "distributed",
    "集中的な": "intensive",
    "広範な": "extensive",
    "局所的な": "local",
    "大域的な": "global",
    "全体的な": "overall",
    "部分的な": "partial",
    "完全な": "complete",
    "不完全な": "incomplete",
    "十分な": "sufficient",
    "不十分な": "insufficient",
    "過剰な": "excessive",
    "適度な": "moderate",
    "極端な": "extreme",
    "中程度の": "moderate",
    "平均的な": "average",
    "標準的な": "standard",
    "普通の": "ordinary",
    "通常の": "normal",
    "異常な": "abnormal",
    "特異な": "peculiar",
    "独特な": "unique",
    "共通の": "common",
    "稀な": "rare",
    "頻繁な": "frequent",
    "時々の": "occasional",
    "常時の": "constant",
    "恒常的な": "permanent",
    "変動的な": "variable",
    "可変的な": "variable",
    "固定的な": "fixed",
    "柔軟な": "flexible",
    "硬直的な": "rigid",
    "弾性的な": "elastic",
    "塑性的な": "plastic",
    "脆性的な": "brittle",
    "延性的な": "ductile",
    "展性的な": "malleable",
    "多孔質の": "porous",
    "緻密な": "dense",
    "疎な": "sparse",
    "密な": "dense",
    "粗い": "coarse",
    "細かい": "fine",
    "滑らかな": "smooth",
    "粗い": "rough",
    "均一な": "uniform",
    "不均一な": "non-uniform",
    "等方的な": "isotropic",
    "異方的な": "anisotropic",
    "対称的な": "symmetric",
    "非対称的な": "asymmetric",
    "相対的な": "relative",
    "絶対的な": "absolute",
    "客観的な": "objective",
    "主観的な": "subjective",
    "定量的な": "quantitative",
    "定性的な": "qualitative",
    "実験的な": "experimental",
    "計算的な": "computational",
    "シミュレーション的な": "simulation-based",
    "解析的な": "analytical",
    "数値的な": "numerical",
    "近似的な": "approximate",
    "厳密な": "exact",
    "精密な": "precise",
    "粗い": "crude",
    "簡略な": "simplified",
    "詳細な": "detailed",
    "包括的な": "comprehensive",
    "限定的な": "limited",
    "制約的な": "constrained",
    "自由な": "free",
    "独立な": "independent",
    "従属的な": "dependent",
    "相関した": "correlated",
    "無相関な": "uncorrelated",
    "因果的な": "causal",
    "非因果的な": "non-causal",
    "直接的な": "direct",
    "間接的な": "indirect",
    "即時的な": "immediate",
    "遅延的な": "delayed",
    "先行的な": "leading",
    "遅行的な": "lagging",
    "同時的な": "simultaneous",
    "逐次的な": "sequential",
    "並列的な": "parallel",
    "直列的な": "serial",
    "階層的な": "hierarchical",
    "平坦な": "flat",
    "複雑な": "complex",
    "単純な": "simple",
    "簡易な": "simplified",
    "高級な": "advanced",
    "初級な": "elementary",
    "中級な": "intermediate",
    "上級な": "advanced",
    "入門的な": "introductory",
    "基礎的な": "basic",
    "発展的な": "advanced",
    "応用的な": "applied",
    "純粋な": "pure",
    "混合的な": "mixed",
    "単一の": "single",
    "複数の": "multiple",
    "二重の": "double",
    "三重の": "triple",
    "多重の": "multiple",
    "一次的な": "primary",
    "二次的な": "secondary",
    "三次的な": "tertiary",
    "高次の": "higher-order",
    "低次の": "lower-order",
    "零次の": "zeroth-order",
    "一次の": "first-order",
    "二次の": "second-order",
    "三次の": "third-order",
    "線形の": "linear",
    "二次的な": "quadratic",
    "三次的な": "cubic",
    "多項式の": "polynomial",
    "指数的な": "exponential",
    "対数的な": "logarithmic",
    "双曲的な": "hyperbolic",
    "三角的な": "trigonometric",
    "周期的な": "periodic",
    "振動的な": "oscillatory",
    "減衰的な": "decaying",
    "増加的な": "increasing",
    "減少的な": "decreasing",
    "単調な": "monotonic",
    "非単調な": "non-monotonic",
    "凸な": "convex",
    "凹な": "concave",
    "平坦な": "flat",
    "傾斜した": "inclined",
    "水平な": "horizontal",
    "垂直な": "vertical",
    "斜めの": "diagonal",
    "平行な": "parallel",
    "直交した": "orthogonal",
    "垂直な": "perpendicular",
    "同心的な": "concentric",
    "同軸的な": "coaxial",
    "共線的な": "collinear",
    "共面的な": "coplanar",
    "交差した": "intersecting",
    "分離した": "separated",
    "接触した": "contacting",
    "接線的な": "tangential",
    "法線的な": "normal",
    "径方向の": "radial",
    "円周方向の": "circumferential",
    "軸方向の": "axial",
    "半径方向の": "radial",
    "角度方向の": "angular",
    "極座標の": "polar",
    "直交座標の": "Cartesian",
    "球座標の": "spherical",
    "円筒座標の": "cylindrical",
    "楕円座標の": "elliptical",
    "双極座標の": "bipolar",
    "放物線座標の": "parabolic",
    "双曲線座標の": "hyperbolic"
}

def translate_japanese_text(text: str) -> str:
    """Translate Japanese text to English using the translation dictionary."""
    result = text
    # Sort by length (longest first) to avoid partial replacements
    for jp, en in sorted(additional_translations.items(), key=lambda x: len(x[0]), reverse=True):
        result = result.replace(jp, en)
    return result

def main():
    file_path = Path(__file__).parent / "chapter-1.html"

    print(f"Reading {file_path}...")
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    original_content = content

    # Apply translations
    print("Applying part 2 translations...")
    content = translate_japanese_text(content)

    # Count changes
    if content != original_content:
        print(f"Translations applied successfully!")
        print(f"Writing back to {file_path}...")
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print("Done!")
    else:
        print("No changes made.")

if __name__ == "__main__":
    main()
