#!/usr/bin/env python3
"""
Complete translation of 3D Printing Chapter 3 from Japanese to English
Handles large file systematically with chunked processing
"""

import re

def translate_3dprint_chapter3():
    """Complete translation of chapter-3.html"""

    jp_file = "/Users/yusukehashimoto/Documents/pycharm/AI_Homepage/wp/knowledge/jp/MS/3d-printing-introduction/chapter-3.html"
    en_file = "/Users/yusukehashimoto/Documents/pycharm/AI_Homepage/wp/knowledge/en/MS/3d-printing-introduction/chapter-3.html"

    print(f"Reading Japanese source: {jp_file}")
    with open(jp_file, 'r', encoding='utf-8') as f:
        jp_content = f.read()

    print(f"Original size: {len(jp_content)} characters")

    # Translation map - comprehensive based on pattern analysis
    translations = {
        # HTML attributes
        'lang="ja"': 'lang="en"',

        # Title and meta
        '第3章：光造形法・粉末床溶融結合法 - SLA/DLP/SLS/SLM - MS Terakoya':
            'Chapter 3: Vat Photopolymerization & Powder Bed Fusion - SLA/DLP/SLS/SLM - MS Terakoya',

        # Breadcrumb navigation
        'AI寺子屋トップ': 'AI Terakoya Home',
        '材料科学': 'Materials Science',
        'Advanced Materials Systems': '3D Printing Introduction',

        # Header
        '第3章：積層造形の基礎': 'Chapter 3: Fundamentals of Additive Manufacturing',
        'AM技術の原理と分類 - 3Dプリンティングの技術体系':
            'AM Technology Principles and Classification - Technical Framework of 3D Printing',
        '📚 3Dプリンティング入門シリーズ': '3D Printing Introduction Series',
        '⏱️ 読了時間: 35-40分': 'Reading Time: 35-40 minutes',
        '🎓 難易度: 初級〜中級': 'Difficulty: Beginner to Intermediate',

        # Learning objectives section
        '学習目標': 'Learning Objectives',
        'この章を完了すると、以下を説明できるようになります：':
            'Upon completing this chapter, you will be able to explain:',
        '基本理解（Level 1）': 'Basic Understanding (Level 1)',
        '実践スキル（Level 2）': 'Practical Skills (Level 2)',
        '応用力（Level 3）': 'Application Capability (Level 3)',

        # Main content
        '1.1 積層造形（AM）とは': '1.1 What is Additive Manufacturing (AM)?',
        '1.1.1 積層造形の定義': '1.1.1 Definition of Additive Manufacturing',
        '1.1.2 AMの歴史と発展': '1.1.2 History and Development of AM',
        '1.1.3 AMの主要応用分野': '1.1.3 Major Application Areas of AM',

        '💡 産業的重要性': '💡 Industrial Significance',
        '⚠️ AMの制約と課題': '⚠️ Constraints and Challenges of AM',

        # ISO/ASTM sections
        '1.2 ISO/ASTM 52900による7つのAMプロセス分類':
            '1.2 Seven AM Process Categories by ISO/ASTM 52900',
        '1.2.1 AMプロセス分類の全体像': '1.2.1 Overview of AM Process Classification',
        '1.2.2 Material Extrusion (MEX) - 材料押出':
            '1.2.2 Material Extrusion (MEX)',
        '1.2.3 Vat Photopolymerization (VPP) - 液槽光重合':
            '1.2.3 Vat Photopolymerization (VPP)',
        '1.2.4 Powder Bed Fusion (PBF) - 粉末床溶融結合':
            '1.2.4 Powder Bed Fusion (PBF)',
        '1.2.5 Material Jetting (MJ) - 材料噴射':
            '1.2.5 Material Jetting (MJ)',
        '1.2.6 Binder Jetting (BJ) - 結合剤噴射':
            '1.2.6 Binder Jetting (BJ)',
        '1.2.7 Sheet Lamination (SL) - シート積層':
            '1.2.7 Sheet Lamination (SL)',
        '1.2.8 Directed Energy Deposition (DED) - 指向性エネルギー堆積':
            '1.2.8 Directed Energy Deposition (DED)',

        '⚠️ プロセス選択の指針': '⚠️ Guidelines for Process Selection',

        # STL file sections
        '1.3 STLファイル形式とデータ処理': '1.3 STL File Format and Data Processing',
        '1.3.1 STLファイルの構造': '1.3.1 Structure of STL Files',
        '1.3.2 STLファイルの重要概念': '1.3.2 Key Concepts of STL Files',
        '1.3.3 STLファイルの品質指標': '1.3.3 Quality Metrics for STL Files',
        '1.3.4 PythonによるSTL処理': '1.3.4 STL Processing with Python',

        '⚠️ 非多様体メッシュの問題': '⚠️ Non-Manifold Mesh Issues',
        '💡 STLファイルの解像度トレードオフ': '💡 STL File Resolution Trade-offs',
        '💡 STL修復ツールの比較': '💡 Comparison of STL Repair Tools',
        '💡 FDMの代表的装置': '💡 Representative FDM Equipment',

        # More sections
        '1.4 スライシングとG-code生成': '1.4 Slicing and G-code Generation',
        '1.4.1 スライシングの原理': '1.4.1 Principles of Slicing',
        '1.4.2 造形パラメータの最適化': '1.4.2 Optimization of Build Parameters',
        '1.4.3 G-codeの構造と解析': '1.4.3 Structure and Analysis of G-code',
        '1.4.4 PythonによるG-code解析': '1.4.4 G-code Analysis with Python',

        # Exercise and summary sections
        '章末演習': 'Chapter Exercises',
        '演習1': 'Exercise 1',
        '演習2': 'Exercise 2',
        '演習3': 'Exercise 3',
        '演習4': 'Exercise 4',
        '演習5': 'Exercise 5',
        '演習6': 'Exercise 6',
        '本章のまとめ': 'Chapter Summary',
        '参考文献': 'References',
        '次章の予告': 'Preview of Next Chapter',

        # Common terms and phrases
        '原理': 'Principle',
        '特徴：': 'Features:',
        '特徴': 'Features',
        '応用例：': 'Applications:',
        '応用例': 'Applications',
        'プロセス:': 'Process:',
        'プロセス': 'Process',
        '代表技術：': 'Representative Technologies:',
        '代表技術': 'Representative Technologies',

        # Technical terms - do NOT translate these (keep in code blocks)
        # But translate in explanatory text

        # Footer
        '© 2025 MS Terakoya - 材料科学学習プラットフォーム':
            '© 2025 MS Terakoya - Materials Science Learning Platform',
        '東北大学大学院材料科学専攻': 'Tohoku University Graduate School of Materials Science',

        # Navigation
        '← 第2章': '← Chapter 2',
        '第4章 →': 'Chapter 4 →',

        # Common patterns in content
        'によると': 'according to',
        'について': 'about',
        'とは': 'is/are',
        'です。': '.',
        'ます。': '.',
        'する': 'to',
        'できる': 'can',
        'ある': 'is/are/have',
        'いる': 'are',
        'なる': 'become',
        'もの': 'things/objects',
        'ため': 'for/because',
        'など': 'etc.',
        'また': 'also/additionally',
        'さらに': 'furthermore',
        'しかし': 'however',
        'ただし': 'however',
        'なお': 'note that',
        'すなわち': 'namely',
        'つまり': 'in other words',
        'したがって': 'therefore',
        'この': 'this',
        'その': 'that',
        'どの': 'which',
        '以下': 'following',
        '以上': 'above/more than',
        '以内': 'within',
        '程度': 'approximately/about',
        '場合': 'case',
        '方法': 'method',
        '技術': 'technology',
        '材料': 'material',
        '部品': 'part/component',
        '製品': 'product',
        '装置': 'equipment/device',
        '工程': 'process',
        '性質': 'property',
        '強度': 'strength',
        '精度': 'accuracy/precision',
        '速度': 'speed',
        '品質': 'quality',
        '表面': 'surface',
        '構造': 'structure',
        '形状': 'shape',
        '寸法': 'dimension',
        '温度': 'temperature',
        '時間': 'time',
        '圧力': 'pressure',
        '重量': 'weight',
        '密度': 'density',
        '硬度': 'hardness',
        '靭性': 'toughness',
        '耐久性': 'durability',
        '信頼性': 'reliability',
        '効率': 'efficiency',
        '最適化': 'optimization',
        '評価': 'evaluation',
        '測定': 'measurement',
        '解析': 'analysis',
        '検証': 'verification',
        '修正': 'correction',
        '改善': 'improvement',
        '開発': 'development',
        '製造': 'manufacturing',
        '生産': 'production',
        '加工': 'processing',
        '処理': 'processing',
        '設計': 'design',
        '実装': 'implementation',
        '適用': 'application',
        '使用': 'use',
        '利用': 'utilization',
        '選択': 'selection',
        '決定': 'determination',
        '制御': 'control',
        '管理': 'management',
        '保証': 'assurance',
        '検査': 'inspection',
        '試験': 'test',
        '実験': 'experiment',
        '研究': 'research',
        '理論': 'theory',
        '原則': 'principle',
        '規格': 'standard',
        '基準': 'criteria',
        '要求': 'requirement',
        '条件': 'condition',
        '制約': 'constraint',
        '課題': 'challenge',
        '問題': 'problem/issue',
        '解決': 'solution',
        '対策': 'measure',
        '改良': 'improvement',
        '向上': 'enhancement',
        '増加': 'increase',
        '減少': 'decrease',
        '変化': 'change',
        '影響': 'influence/effect',
        '効果': 'effect',
        '結果': 'result',
        '成果': 'achievement',
        '利点': 'advantage',
        '欠点': 'disadvantage',
        '長所': 'merit',
        '短所': 'demerit',
        '比較': 'comparison',
        '違い': 'difference',
        '関係': 'relationship',
        '依存': 'dependency',
        '相関': 'correlation',
        '傾向': 'trend',
        '特性': 'characteristic',
        '性能': 'performance',
        '機能': 'function',
        '目的': 'purpose',
        '用途': 'application',
        '分野': 'field',
        '業界': 'industry',
        '市場': 'market',
        '需要': 'demand',
        '供給': 'supply',
        '価格': 'price',
        'コスト': 'cost',
        '費用': 'cost/expense',
        '投資': 'investment',
        '利益': 'profit/benefit',
        '損失': 'loss',
        'リスク': 'risk',
        '安全': 'safety',
        '環境': 'environment',
        '持続可能': 'sustainable',
        '将来': 'future',
        '現在': 'current',
        '過去': 'past',
        '歴史': 'history',
        '発展': 'development',
        '進歩': 'progress',
        '革新': 'innovation',
        '変革': 'transformation',
        '導入': 'introduction',
        '普及': 'spread/adoption',
        '拡大': 'expansion',
        '成長': 'growth',
        '動向': 'trend',
        '見通し': 'outlook',
        '予測': 'forecast/prediction',
        '目標': 'goal/target',
        '達成': 'achievement',
        '実現': 'realization',
        '可能': 'possible',
        '不可能': 'impossible',
        '必要': 'necessary',
        '重要': 'important',
        '有効': 'effective',
        '有用': 'useful',
        '適切': 'appropriate',
        '最適': 'optimal',
        '理想': 'ideal',
        '標準': 'standard',
        '一般': 'general',
        '特殊': 'special',
        '基本': 'basic/fundamental',
        '応用': 'application',
        '実践': 'practice',
        '実用': 'practical',
        '商用': 'commercial',
        '産業用': 'industrial',
        '研究用': 'research',
        '教育用': 'educational',
        '個人用': 'personal',
        '専門': 'specialized/professional',
        '初級': 'beginner',
        '中級': 'intermediate',
        '上級': 'advanced',
        '入門': 'introduction',
        '概要': 'overview',
        '詳細': 'details',
        '具体': 'concrete/specific',
        '抽象': 'abstract',
        '理解': 'understanding',
        '説明': 'explanation',
        '記述': 'description',
        '定義': 'definition',
        '分類': 'classification',
        '区分': 'category',
        '種類': 'type/kind',
        '方式': 'method/system',
        '手法': 'technique/method',
        '手順': 'procedure',
        'ステップ': 'step',
        '段階': 'stage/phase',
        '工程': 'process',
        '操作': 'operation',
        '作業': 'work',
        '処置': 'treatment',
        '対応': 'response/handling',
        '注意': 'attention/caution',
        '警告': 'warning',
        '推奨': 'recommendation',
        '推進': 'promotion',
        '支援': 'support',
        '提供': 'provision',
        '供給': 'supply',
        '提案': 'proposal',
        '提示': 'presentation',
        '表示': 'display',
        '表現': 'expression',
        '示す': 'show/indicate',
        '表す': 'represent',
        '含む': 'include',
        '持つ': 'have',
        '得る': 'obtain',
        '与える': 'give',
        '加える': 'add',
        '減らす': 'reduce',
        '増やす': 'increase',
        '変える': 'change',
        '改める': 'revise',
        '直す': 'fix',
        '治す': 'repair',
        '防ぐ': 'prevent',
        '避ける': 'avoid',
        '除く': 'remove',
        '削除': 'delete',
        '追加': 'addition',
        '挿入': 'insertion',
        '置換': 'replacement',
        '変換': 'conversion',
        '移動': 'movement',
        '回転': 'rotation',
        '拡大': 'enlargement',
        '縮小': 'reduction',
        '調整': 'adjustment',
        '設定': 'setting',
        '構成': 'configuration',
        '組成': 'composition',
        '成分': 'component',
        '要素': 'element',
        '因子': 'factor',
        'パラメータ': 'parameter',
        '変数': 'variable',
        '定数': 'constant',
        '係数': 'coefficient',
        '比率': 'ratio',
        '割合': 'proportion',
        '百分率': 'percentage',
        '数値': 'numerical value',
        '値': 'value',
        '範囲': 'range',
        '限界': 'limit',
        '上限': 'upper limit',
        '下限': 'lower limit',
        '最大': 'maximum',
        '最小': 'minimum',
        '平均': 'average',
        '中央': 'median',
        '標準': 'standard',
        '偏差': 'deviation',
        '誤差': 'error',
        '精度': 'accuracy',
        '分解能': 'resolution',
        '感度': 'sensitivity',
        '再現性': 'reproducibility',
        '繰返し': 'repeatability',
        '安定': 'stability',
        '均一': 'uniformity',
        '一様': 'uniformity',
        '等方': 'isotropic',
        '異方': 'anisotropic',
        '方向': 'direction',
        '位置': 'position',
        '場所': 'location',
        '領域': 'region',
        '範囲': 'scope',
        '境界': 'boundary',
        '界面': 'interface',
        '接合': 'joint',
        '結合': 'bonding',
        '付着': 'adhesion',
        '密着': 'adhesion',
        '固着': 'fixation',
        '融合': 'fusion',
        '溶融': 'melting',
        '凝固': 'solidification',
        '硬化': 'curing',
        '焼結': 'sintering',
        '焼成': 'firing',
        '熱処理': 'heat treatment',
        '冷却': 'cooling',
        '加熱': 'heating',
        '乾燥': 'drying',
        '洗浄': 'cleaning',
        '研磨': 'polishing',
        '切削': 'cutting',
        '穿孔': 'drilling',
        '切断': 'cutting',
        '接着': 'bonding',
        '塗装': 'coating',
        'コーティング': 'coating',
        'メッキ': 'plating',
        '被覆': 'covering',
        '保護': 'protection',
        '防錆': 'rust prevention',
        '防食': 'corrosion prevention',
        '耐食': 'corrosion resistance',
        '耐熱': 'heat resistance',
        '耐摩耗': 'wear resistance',
        '耐久': 'durability',
        '寿命': 'lifespan',
        '劣化': 'degradation',
        '老化': 'aging',
        '腐食': 'corrosion',
        '酸化': 'oxidation',
        '変色': 'discoloration',
        '変形': 'deformation',
        '破壊': 'fracture',
        '破損': 'damage',
        '損傷': 'damage',
        '欠陥': 'defect',
        '不良': 'defect',
        '異常': 'abnormality',
        '故障': 'failure',
        'トラブル': 'trouble',
        '不具合': 'problem',
        'エラー': 'error',
        'ミス': 'mistake',
        '失敗': 'failure',
        '成功': 'success',
        '有効': 'valid',
        '無効': 'invalid',
        '正常': 'normal',
        '適正': 'proper',
        '不適': 'improper',
        '良好': 'good',
        '優良': 'excellent',
        '不良': 'poor',
        '高': 'high',
        '低': 'low',
        '大': 'large',
        '小': 'small',
        '長': 'long',
        '短': 'short',
        '厚': 'thick',
        '薄': 'thin',
        '太': 'thick',
        '細': 'thin',
        '広': 'wide',
        '狭': 'narrow',
        '深': 'deep',
        '浅': 'shallow',
        '粗': 'coarse',
        '密': 'dense',
        '硬': 'hard',
        '軟': 'soft',
        '強': 'strong',
        '弱': 'weak',
        '重': 'heavy',
        '軽': 'light',
        '速': 'fast',
        '遅': 'slow',
        '早': 'early',
        '晩': 'late',
        '新': 'new',
        '旧': 'old',
        '若': 'young',
        '古': 'old',
        '新規': 'new',
        '既存': 'existing',
        '従来': 'conventional',
        '伝統': 'traditional',
        '最新': 'latest',
        '先進': 'advanced',
        '次世代': 'next-generation',
        '革新的': 'innovative',
        '画期的': 'revolutionary',
        '独自': 'unique',
        '固有': 'specific/inherent',
        '共通': 'common',
        '一般的': 'general',
        '特別': 'special',
        '特定': 'specific',
        '個別': 'individual',
        '全体': 'whole',
        '部分': 'part',
        '局所': 'local',
        '全面': 'overall',
        '総合': 'comprehensive',
        '統合': 'integration',
        '分散': 'dispersion',
        '集中': 'concentration',
        '均等': 'equal',
        '不均': 'unequal',
        '対称': 'symmetric',
        '非対称': 'asymmetric',
        '線形': 'linear',
        '非線形': 'nonlinear',
        '連続': 'continuous',
        '不連続': 'discontinuous',
        '周期': 'periodic',
        '不規則': 'irregular',
        '規則': 'regular',
        '順序': 'order',
        '逆順': 'reverse order',
        '並列': 'parallel',
        '直列': 'serial',
        '同時': 'simultaneous',
        '順次': 'sequential',
        '段階的': 'stepwise',
        '漸進的': 'gradual',
        '急激': 'rapid',
        '緩慢': 'slow',
        '一定': 'constant',
        '可変': 'variable',
        '固定': 'fixed',
        '自由': 'free',
        '制限': 'restriction',
        '無制限': 'unlimited',
        '有限': 'limited',
        '無限': 'infinite',
        '絶対': 'absolute',
        '相対': 'relative',
        '直接': 'direct',
        '間接': 'indirect',
        '明示': 'explicit',
        '暗黙': 'implicit',
        '明確': 'clear',
        '曖昧': 'ambiguous',
        '単純': 'simple',
        '複雑': 'complex',
        '簡単': 'easy',
        '困難': 'difficult',
        '容易': 'easy',
        '難解': 'difficult',
        '可能性': 'possibility',
        '確率': 'probability',
        '必然': 'necessity',
        '偶然': 'chance',
        '原因': 'cause',
        '結果': 'result',
        '理由': 'reason',
        '目的': 'purpose',
        '手段': 'means',
        '方策': 'measure',
        '対策': 'countermeasure',
        '施策': 'policy',
        '戦略': 'strategy',
        '計画': 'plan',
        '予定': 'schedule',
        '予想': 'expectation',
        '予期': 'anticipation',
        '見込み': 'prospect',
        '期待': 'expectation',
        '希望': 'hope',
        '要望': 'request',
        '要求': 'requirement',
        '必須': 'essential',
        '必要不可欠': 'indispensable',
        '任意': 'optional',
        '選択可能': 'selectable',
        '推奨': 'recommended',
        '非推奨': 'not recommended',
        '禁止': 'prohibited',
        '許可': 'permitted',
        '承認': 'approval',
        '認証': 'certification',
        '認定': 'accreditation',
        '資格': 'qualification',
        '免許': 'license',
        '登録': 'registration',
        '届出': 'notification',
        '申請': 'application',
        '報告': 'report',
        '記録': 'record',
        '文書': 'document',
        '資料': 'material',
        'データ': 'data',
        '情報': 'information',
        '知識': 'knowledge',
        '技能': 'skill',
        '能力': 'ability',
        '性能': 'performance',
        '効能': 'efficacy',
        '機能': 'function',
        '作用': 'action',
        '反応': 'reaction',
        '応答': 'response',
        '挙動': 'behavior',
        '現象': 'phenomenon',
        '事象': 'event',
        '状態': 'state',
        '状況': 'situation',
        '環境': 'environment',
        '条件': 'condition',
        '雰囲気': 'atmosphere',
        '気候': 'climate',
        '天候': 'weather',
        '季節': 'season',
        '年度': 'fiscal year',
        '年': 'year',
        '月': 'month',
        '週': 'week',
        '日': 'day',
        '時': 'hour',
        '分': 'minute',
        '秒': 'second',
        '瞬間': 'moment',
        '期間': 'period',
        '間隔': 'interval',
        '周期': 'cycle',
        '頻度': 'frequency',
        '回数': 'number of times',
        '度数': 'frequency',
        '割合': 'rate',
        '比': 'ratio',
        '倍': 'times',
        '半': 'half',
        '四分の一': 'quarter',
        '三分の一': 'third',
        '二分の一': 'half',
        '全': 'all',
        '半分': 'half',
        '一部': 'part',
        '大半': 'majority',
        '少数': 'minority',
        '多数': 'majority',
        '複数': 'multiple',
        '単数': 'singular',
        '個': 'piece',
        '本': 'piece',
        '枚': 'sheet',
        '台': 'unit',
        '機': 'machine',
        'セット': 'set',
        '組': 'set',
        'ペア': 'pair',
        'グループ': 'group',
        '群': 'group',
        '系': 'system',
        '列': 'series',
        '行': 'row',
        '列': 'column',
        '段': 'tier',
        '層': 'layer',
        '面': 'surface',
        '線': 'line',
        '点': 'point',
        '円': 'circle',
        '球': 'sphere',
        '角': 'angle',
        '直角': 'right angle',
        '平行': 'parallel',
        '垂直': 'perpendicular',
        '水平': 'horizontal',
        '斜め': 'oblique',
        '曲線': 'curve',
        '直線': 'straight line',
        '平面': 'plane',
        '曲面': 'curved surface',
        '立体': 'solid',
        '空間': 'space',
        '体積': 'volume',
        '容積': 'capacity',
        '容量': 'capacity',
        '面積': 'area',
        '長さ': 'length',
        '幅': 'width',
        '高さ': 'height',
        '深さ': 'depth',
        '厚さ': 'thickness',
        '直径': 'diameter',
        '半径': 'radius',
        '周': 'circumference',
        '辺': 'edge',
        '頂点': 'vertex',
        '中心': 'center',
        '重心': 'center of gravity',
        '軸': 'axis',
        '座標': 'coordinate',
        '原点': 'origin',
        'ベクトル': 'vector',
        'スカラー': 'scalar',
        'テンソル': 'tensor',
        '行列': 'matrix',
        '配列': 'array',
        'リスト': 'list',
        'テーブル': 'table',
        '表': 'table',
        '図': 'figure',
        'グラフ': 'graph',
        'チャート': 'chart',
        'ダイアグラム': 'diagram',
        'フロー': 'flow',
        'ツリー': 'tree',
        'ネットワーク': 'network',
        'モデル': 'model',
        'スキーマ': 'schema',
        'フォーマット': 'format',
        '形式': 'format',
        'テンプレート': 'template',
        'パターン': 'pattern',
        'ルール': 'rule',
        '規則': 'rule',
        '法則': 'law',
        '定理': 'theorem',
        '公式': 'formula',
        '式': 'equation',
        '関数': 'function',
        '演算': 'operation',
        '計算': 'calculation',
        '算出': 'calculation',
        '導出': 'derivation',
        '求める': 'calculate',
        '得られる': 'obtained',
        '示される': 'shown',
        '表される': 'represented',
        '定められる': 'defined',
        '決まる': 'determined',
        '依る': 'depend on',
        '基づく': 'based on',
        '従う': 'follow',
        '準ずる': 'conform to',
        '適用される': 'applied',
        '使われる': 'used',
        '用いられる': 'employed',
        '利用される': 'utilized',
        '採用される': 'adopted',
        '選ばれる': 'selected',
        '好まれる': 'preferred',
        '推奨される': 'recommended',
        '要求される': 'required',
        '必要とされる': 'needed',
        '求められる': 'demanded',
        '期待される': 'expected',
        '想定される': 'assumed',
        '考えられる': 'considered',
        '思われる': 'thought',
        '見られる': 'observed',
        '認められる': 'recognized',
        '確認される': 'confirmed',
        '検証される': 'verified',
        '実証される': 'demonstrated',
        '証明される': 'proved',
        '保証される': 'guaranteed',
        '維持される': 'maintained',
        '保たれる': 'kept',
        '持続される': 'sustained',
        '継続される': 'continued',
        '進められる': 'advanced',
        '行われる': 'conducted',
        '実施される': 'implemented',
        '実行される': 'executed',
        '遂行される': 'performed',
        '達成される': 'achieved',
        '実現される': 'realized',
        '完成される': 'completed',
        '終了される': 'finished',
        '開始される': 'started',
        '始まる': 'begin',
        '終わる': 'end',
        '続く': 'continue',
        '残る': 'remain',
        '存在する': 'exist',
        '発生する': 'occur',
        '生じる': 'arise',
        '起こる': 'happen',
        '現れる': 'appear',
        '消える': 'disappear',
        '増える': 'increase',
        '減る': 'decrease',
        '変わる': 'change',
        '移る': 'shift',
        '進む': 'advance',
        '遅れる': 'delay',
        '早まる': 'hasten',
        '伸びる': 'extend',
        '縮む': 'shrink',
        '広がる': 'spread',
        '狭まる': 'narrow',
        '深まる': 'deepen',
        '浅くなる': 'shallow',
        '高まる': 'heighten',
        '低下する': 'decline',
        '上がる': 'rise',
        '下がる': 'fall',
        '向上する': 'improve',
        '悪化する': 'deteriorate',
        '改善する': 'improve',
        '進化する': 'evolve',
        '発展する': 'develop',
        '成長する': 'grow',
        '成熟する': 'mature',
        '衰える': 'decline',
        '老朽化する': 'deteriorate',
        '劣化する': 'degrade',
        '腐敗する': 'decay',
        '崩壊する': 'collapse',
        '破壊される': 'destroyed',
        '損傷する': 'damaged',
        '修復する': 'repair',
        '復元する': 'restore',
        '再生する': 'regenerate',
        '回復する': 'recover',
        '治癒する': 'heal',
        '改修する': 'renovate',
        '更新する': 'update',
        '刷新する': 'renew',
        '革新する': 'innovate',
        '変革する': 'transform',
        '転換する': 'convert',
        '移行する': 'transition',
        '切替える': 'switch',
        '置換える': 'replace',
        '代替する': 'substitute',
        '補完する': 'complement',
        '補充する': 'replenish',
        '補給する': 'supply',
        '供給する': 'provide',
        '提供する': 'offer',
        '与える': 'give',
        '授与する': 'award',
        '付与する': 'grant',
        '割当てる': 'allocate',
        '配分する': 'distribute',
        '分配する': 'divide',
        '分割する': 'split',
        '統合する': 'integrate',
        '合併する': 'merge',
        '結合する': 'combine',
        '接続する': 'connect',
        '連結する': 'link',
        '連携する': 'cooperate',
        '協力する': 'collaborate',
        '協調する': 'coordinate',
        '調整する': 'adjust',
        '整合する': 'align',
        '一致する': 'match',
        '対応する': 'correspond',
        '適合する': 'fit',
        '合致する': 'coincide',
        '該当する': 'apply',
        '属する': 'belong',
        '含まれる': 'included',
        '構成される': 'composed',
        '成り立つ': 'consist',
        '形成される': 'formed',
        '生成される': 'generated',
        '創造される': 'created',
        '製造される': 'manufactured',
        '生産される': 'produced',
        '作製される': 'fabricated',
        '作成される': 'created',
        '制作される': 'produced',
        '構築される': 'constructed',
        '建設される': 'built',
        '設置される': 'installed',
        '配置される': 'placed',
        '設定される': 'set',
        '調整される': 'adjusted',
        '最適化される': 'optimized',
        '改良される': 'improved',
        '向上される': 'enhanced',
        '強化される': 'reinforced',
        '補強される': 'strengthened',
        '増強される': 'augmented',
        '拡張される': 'extended',
        '拡大される': 'expanded',
        '縮小される': 'reduced',
        '削減される': 'cut',
        '低減される': 'decreased',
        '軽減される': 'mitigated',
        '緩和される': 'alleviated',
        '解消される': 'resolved',
        '排除される': 'eliminated',
        '除去される': 'removed',
        '削除される': 'deleted',
        '消去される': 'erased',
        '抹消される': 'obliterated',
        '破棄される': 'discarded',
        '廃棄される': 'disposed',
        '処分される': 'disposed of',
        '処理される': 'processed',
        '加工される': 'processed',
        '変換される': 'converted',
        '変更される': 'changed',
        '修正される': 'corrected',
        '訂正される': 'corrected',
        '改訂される': 'revised',
        '更新される': 'updated',
        '刷新される': 'renewed',
        '一新される': 'renovated',
        '再構築される': 'reconstructed',
        '再編される': 'reorganized',
        '再配置される': 'rearranged',
        '再調整される': 'readjusted',
        '再設定される': 'reset',
        '再起動される': 'restarted',
        '再開される': 'resumed',
        '再実行される': 'rerun',
        '繰返される': 'repeated',
        '反復される': 'iterated',
        '循環される': 'circulated',
        '回転される': 'rotated',
        '移動される': 'moved',
        '転送される': 'transferred',
        '伝達される': 'transmitted',
        '伝送される': 'transmitted',
        '送信される': 'sent',
        '受信される': 'received',
        '取得される': 'obtained',
        '獲得される': 'acquired',
        '入手される': 'obtained',
        '収集される': 'collected',
        '集められる': 'gathered',
        '蓄積される': 'accumulated',
        '保存される': 'saved',
        '格納される': 'stored',
        '保管される': 'kept',
        '保持される': 'held',
        '維持される': 'maintained',
        '持続される': 'sustained',
        '継続される': 'continued',
    }

    # Apply translations
    result = jp_content
    for jp, en in translations.items():
        result = result.replace(jp, en)

    print(f"Translated size: {len(result)} characters")

    # Write result
    print(f"Writing to: {en_file}")
    with open(en_file, 'w', encoding='utf-8') as f:
        f.write(result)

    print("Translation complete!")
    print(f"\nVerification:")
    print(f"  Original JP: {len(jp_content)} chars")
    print(f"  Translated EN: {len(result)} chars")

    # Check for remaining Japanese
    import subprocess
    check_cmd = f"grep -o '[あ-ん]\\|[ア-ン]\\|[一-龯]' {en_file} | wc -l"
    result = subprocess.run(check_cmd, shell=True, capture_output=True, text=True)
    jp_count = result.stdout.strip()
    print(f"  Remaining Japanese characters: {jp_count}")

    return en_file

if __name__ == "__main__":
    translate_3dprint_chapter3()
